import { Server } from "../types/response/server.response";

export const MOCK_SERVERS: Server[] = [
  {
    id: "srv-001",
    name: "Production API",
    ip_address: "192.168.1.10",
    status: "up",
    response_time_ms: 42,
    uptime_percentage: 99.98,
    region: "us-east-1",
    last_checked: new Date(Date.now() - 30_000).toISOString(),
    tags: ["production", "api"],
    description: "Primary production API server handling all client requests.",
  },
  {
    id: "srv-002",
    name: "Database Primary",
    ip_address: "192.168.1.20",
    status: "up",
    response_time_ms: 8,
    uptime_percentage: 99.99,
    region: "us-east-1",
    last_checked: new Date(Date.now() - 15_000).toISOString(),
    tags: ["production", "database"],
    description: "PostgreSQL primary node — all write operations.",
  },
  {
    id: "srv-003",
    name: "Web Server EU",
    ip_address: "10.0.0.5",
    status: "up",
    response_time_ms: 78,
    uptime_percentage: 99.91,
    region: "eu-west-1",
    last_checked: new Date(Date.now() - 60_000).toISOString(),
    tags: ["production", "web"],
    description: "European CDN-backed web server serving static assets.",
  },
  {
    id: "srv-004",
    name: "Cache Layer",
    ip_address: "192.168.1.30",
    status: "degraded",
    response_time_ms: 320,
    uptime_percentage: 97.4,
    region: "us-east-1",
    last_checked: new Date(Date.now() - 45_000).toISOString(),
    tags: ["cache", "redis"],
    description: "Redis cluster experiencing elevated latency.",
  },
  {
    id: "srv-005",
    name: "Mail Service",
    ip_address: "10.0.0.12",
    status: "down",
    response_time_ms: 0,
    uptime_percentage: 89.5,
    region: "us-west-2",
    last_checked: new Date(Date.now() - 120_000).toISOString(),
    tags: ["email", "smtp"],
    description: "SMTP relay — currently unreachable.",
  },
  {
    id: "srv-006",
    name: "Analytics Worker",
    ip_address: "10.0.0.22",
    status: "up",
    response_time_ms: 55,
    uptime_percentage: 99.7,
    region: "us-west-2",
    last_checked: new Date(Date.now() - 20_000).toISOString(),
    tags: ["analytics", "worker"],
    description: "Background job processing for analytics pipelines.",
  },
  {
    id: "srv-007",
    name: "Staging API",
    ip_address: "172.16.0.5",
    status: "up",
    response_time_ms: 91,
    uptime_percentage: 98.2,
    region: "eu-central-1",
    last_checked: new Date(Date.now() - 90_000).toISOString(),
    tags: ["staging", "api"],
    description: "Staging environment for pre-production testing.",
  },
  {
    id: "srv-008",
    name: "Auth Service",
    ip_address: "192.168.1.50",
    status: "up",
    response_time_ms: 23,
    uptime_percentage: 99.95,
    region: "us-east-1",
    last_checked: new Date(Date.now() - 10_000).toISOString(),
    tags: ["production", "auth"],
    description: "JWT-based authentication and session management.",
  },
];
